name: easyDesign
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.2.0
  - blinker=1.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cryptography=42.0.5
  - exceptiongroup=1.2.0
  - fastapi=0.110.0
  - frozenlist=1.4.1
  - gast=0.3.3
  - google-auth=2.28.1
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - h11=0.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=3.6
  - importlib-metadata=7.0.1
  - keras-preprocessing=1.1.2
  - ld_impl_linux-64=2.40
  - libabseil=20220623.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.12
  - libprotobuf=3.20.3
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - markdown=3.5.2
  - markupsafe=2.1.5
  - multidict=6.0.5
  - ncurses=6.4
  - numpy=1.17.5
  - oauthlib=3.2.2
  - openssl=3.2.1
  - opt_einsum=3.3.0
  - pandas=1.2.3
  - pip=24.0
  - protobuf=3.20.3
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydantic=2.6.3
  - pydantic-core=2.16.3
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-multipart=0.0.9
  - python_abi=3.8
  - pytz=2024.1
  - pyu2f=0.1.5
  - re2=2022.06.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.4.1
  - setuptools=59.8.0
  - six=1.16.0
  - sniffio=1.3.1
  - starlette=0.36.3
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.5.0
  - termcolor=2.4.0
  - tk=8.6.13
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - urllib3=2.2.1
  - uvicorn=0.27.1
  - werkzeug=3.0.1
  - wheel=0.42.0
  - wrapt=1.16.0
  - xz=5.2.6
  - yarl=1.9.4
  - zipp=3.17.0
  - zlib=1.2.13

